// DO NOT EDIT THIS FILE DIRECTLY
// This file is a template for the ecosystem.config.js file that should be created in the same directory.
// Replace the placeholders with your own values and save it as ecosystem.config.js.
// The ecosystem.config.js file is used by PM2 to manage the processes.
// To start the miner process, run `pm2 start ecosystem.config.js --only miner`.
// To start the validator process, run `pm2 start ecosystem.config.js --only validator`.
module.exports = {
  apps: [
    {
      name: "miner",
      script: "miner.py",
      interpreter: "python3", // replace with "python3" if you don't use a virtual environment
      cwd: "neurons",
      kill_timeout: 3000, // just to allow the miner to clean up before being killed
      args: [
        "--netuid 2",
        "--wallet.name {your_miner_key_name}", // replace with your miner key name
        "--wallet.hotkey {your_miner_hotkey_name}", // replace with your miner hotkey name
      ].join(" "),
    },
    {
      name: "validator",
      script: "validator.py",
      interpreter: "python3", // replace with "python3" if you don't use a virtual environment
      cwd: "neurons",
      kill_timeout: 3000, // just to allow the miner to clean up before being killed
      args: [
        "--netuid 2",
        "--wallet.name {your_validator_key_name}", // replace with your validator key name
        "--wallet.hotkey {your_validator_hotkey_name}", // replace with your validator hotkey name
      ].join(" "),
    },
  ],
};
